### ISSUE TITLE
大佬，你这个手台的抬手是咋实现的？

### ISSUE THREAD

**Issue by MCredbear** [fangxx3863/RPunithm-Web#1]
我只看到了朋友给我转发了两张图，很好奇你这个没有两边支红外传感器的抬手是怎么实现的。如果可以的话你可以卖我一台这个手台吗？

**Comment by fangxx3863** [comment]
【闲鱼】https://m.tb.cn/h.5cApGZP?tk=HsOIdFOv6nu
